### ISSUE TITLE
The Term Definition Search

### ISSUE THREAD

**Issue by CloutAPK** [NightfallAlicorn/urban-dictionary#5]
So, if you run this `let word = "wwawdwadawdawcafdaw";
    
    ud.term(word, (error, entries, tags, sounds) => {
        if (error) {
          console.error(error.message)
        } else {
          console.log(entries[0].word)
          console.log(entries[0].definition)
          console.log(entries[0].example)
        }
      })`
then you will notice, that you get an error, because urban dictionary cant run that code, so how can I stop it from getting errors when people are searching words with no definition?

**Comment by NightfallAlicorn** [comment]
It appears the issue is caused when the promise doesn't have a catch method attached even if the user is using the callback method. I've added a unhandledRejection to the process catch to prevent the error. Although, I don't know if this the best way to solve it but I couldn't find any better solution.

I've pushed the fix.
